# Generated by Django 5.0.7 on 2024-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='load_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
