# Generated by Django 5.0.7 on 2024-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_alter_employee_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.TextField(max_length=100),
        ),
    ]
